### ISSUE TITLE
Video not playing on Windows

### ISSUE THREAD

**Issue by davidslaby** [monyone/zlplayer#1]
Endless loading of web page

Video loaded (verified by console.log placed in load callback) without any error message in console

After play showing just empty video container

---------------------------------------------

Windows 10
Chrome  97.0.4692.71

**Comment by monyone** [comment]
Sorry for late response.
I tried chrome on Window10, play successly.

please more infomation live streaming settings. Thanks!

**Comment by davidslaby** [comment]
Hi @monyone, it's okay.

I'm not sure what are you asking for :(

The stream configuration?

**Comment by monyone** [comment]
> The stream configuration?

Yes. Please write stream configuration.

**Comment by davidslaby** [comment]
@monyone, I have prepared a sample stream for you :)

https://drive.google.com/file/d/1QLJKSnMocvii02OiqAK2gjF_NOJ2UrI4/view?usp=sharing

**Comment by davidslaby** [comment]
Hi @monyone, have you already checked, please? Do you have any update? :)
 
 Thank you!

**Comment by monyone** [comment]
@davidslaby sorry for late response.

WebCodecs requires SecureContext, so https or localhost required.
Are you hosted in http (not SecureContext)?

**Comment by davidslaby** [comment]
@monyone The video is hosted on `streamUrl: 'http://127.0.0.1:1337'` after you run the script I attached within G Drive link above.
But I have tried even with secured HTTPS stream, and it also didn't work properly.

**Comment by monyone** [comment]
@davidslaby
SecureContext required by hosted website. (use zlplayer page) 
Not stream url.

**Comment by davidslaby** [comment]
@monyone Okay, I will check once again and let you know. Thank you.
