### ISSUE TITLE
Calling Player stop() method ends up with exception due to locked OutputStream when using hotReload

### ISSUE THREAD

**Issue by krpecd** [monyone/zlplayer#2]
I'm implementing this library into React application. While using hotReload the app is ending on this exception:

```
Uncaught (in promise) TypeError: Failed to execute 'cancel' on 'ReadableStream': Cannot cancel a locked stream
```

I created a fix in forked repository: [fix commit](https://github.com/krpecd/zlplayer/commit/86fa18663b1e5eddf45a08f1e1ea0416b3babbeb)

**Comment by monyone** [comment]
sorry for late response. I merged them.
